- ArmoniK.Extensions.Csharp.sln
- Common/ArmoniK.DevelopmentKit.Common/ArmoniK.DevelopmentKit.Common.csproj
- Common/ArmoniK.DevelopmentKit.Common/Exceptions/WorkerApiExceptions.cs
- Common/ArmoniK.DevelopmentKit.Common/IFileAdaptater.cs
- SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Tests/EndToEnd.Tests/appsettings.json
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/Adaptater/FsAdaptater.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/Adaptater/S3Adaptater.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/ZipArchiver.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/AppsLoader.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/ServiceRequestContext.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Services/ComputerService.cs
- WorkerApi/tests/WorkerApiTests/UnitTest1.cs
- WorkerApi/tests/WorkerApiTests/WorkerApiTests.csproj
Fix enhancement [Issue 19](https://github.com/aneoconsulting/ArmoniK/issues/19)
> feature: Add S3 Object storage in Dynamic dll loading

- ArmoniK.Extensions.Csharp.sln.DotSettings
- Common/StreamWrapper/src/ArmoniK.Extensions.Common.StreamWrapper.csproj
- Common/StreamWrapper/src/Client/SubmitterClientExt.cs
- Common/StreamWrapper/src/Worker/TaskHandler.cs
- Common/StreamWrapper/src/Worker/TaskRequestExtensions.cs
- Add some comments
- Remove some unnecessary copies
> stream wrapper clean

- Common/StreamWrapper/src/Client/SubmitterClientExt.cs
Link to Issue https://github.com/aneoconsulting/ArmoniK/issues/245
> Better Error display from TryGetResult

- Common/ArmoniK.DevelopmentKit.Common/Submitter/BaseClientSubmitter.cs
- Common/StreamWrapper/src/Client/SubmitterClientExt.cs
Manage empty result and null when error is happening
> Manage Empty result which differ from error returning null

- Common/EndToEnd.Tests/Tests/CheckRandomException/RandomExceptionClient.cs
- Common/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnfiedAPITest.cs
- Common/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPIAdminTestClient.cs
- UnifiedApi/Client/ArmoniK.DevelopmentKit.Client.csproj
- UnifiedApi/Client/Factory/ServiceFactory.cs
- UnifiedApi/Client/Factory/SessionServiceFactory.cs
- UnifiedApi/Client/Services/Admin/AdminMonitoringService.cs
- UnifiedApi/Client/Services/Admin/ServiceAdmin.cs
Slow down submit function to avoid Grpc Error protocol
> Admin & Monitoring API

- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Dockerfile
Changed debugger location to fix https://github.com/aneoconsulting/ArmoniK/issues/339
> Fixed vs-debugger location

- Common/EndToEnd.Tests/Tests/CheckTypeOfSubmission/CheckAllSubmissionsClient.cs
- Common/StreamWrapper/src/Client/SubmitterClientExt.cs
Issue https://github.com/aneoconsulting/ArmoniK/issues/101
> Fix issue with enhance your calm and error protocol with GRPC submit

- ArmoniK.Extensions.Csharp.sln.DotSettings
- Common/ArmoniK.DevelopmentKit.Common/IEnumerableExt.cs
- Common/ArmoniK.DevelopmentKit.Common/Submitter/BaseClientSubmitter.cs
- Common/StreamWrapper/tests/Common/TestPayload.cs
- DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Client/Service.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Services/ComputerService.cs
https://github.com/aneoconsulting/ArmoniK/issues/399
> Avoid wait function

- Common/ArmoniK.DevelopmentKit.Common/Submitter/BaseClientSubmitter.cs
- Common/EndToEnd.Tests/ArmoniK.EndToEndTests.csproj
- Common/EndToEnd.Tests/Tests/CheckTypeOfSubmission/CheckAllSubmissionsClient.cs
- Common/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPITestClient.cs
- UnifiedApi/Client/Services/Common/AbstractClientService.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
PR for https://github.com/aneoconsulting/ArmoniK/issues/411
> Optimize result request for sequential submit in UnifiedApi

- .editorconfig
Fix https://github.com/aneoconsulting/ArmoniK/issues/472
> Raised IDisposable not disposed severity

- Client/src/ArmoniK.DevelopmentKit.Client.Common/Submitter/BaseClientSubmitter.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/482
> Improve memory usage

- Client/src/ArmoniK.DevelopmentKit.Client.Common/Submitter/BaseClientSubmitter.cs
GetResultStatus was modifying the Hashset idStatus it was iterating on. This PR fixes it.
> Fix GetResultStatus

- Common/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPITestClient.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/509
> Refactor results acquisition in background thread for Unified API

- Tests/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPIAdminTestClient.cs
- Tests/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPITestClient.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
Fix https://github.com/aneoconsulting/ArmoniK/issues/522
Fix #72
> Fixing issue 522

- Tests/EndToEnd.Tests/Tests/CheckSubtaskingTree_SymphonySDK/SubtaskingTreeClient.cs
- Tests/EndToEnd.Tests/Tests/CheckSubtaskingTree_SymphonySDK/SubtaskingTreeTest.cs
- Tests/endToEndTests.sh
add subtasking for symphony sdk style
update script sendToEndTests.sh to be abble to run in local wsl
> 535 subtasking symphony style and EndToEnd local wsl

- .github/workflows/build.yml
- Client/src/ArmoniK.DevelopmentKit.Client.Common/ArmoniK.DevelopmentKit.Client.Common.csproj
- Client/src/ArmoniK.DevelopmentKit.Client.Common/Status/ResultStatusCollection.cs
- Client/src/ArmoniK.DevelopmentKit.Client.Common/Status/ResultStatusData.cs
- Client/src/ArmoniK.DevelopmentKit.Client.Common/Submitter/BaseClientSubmitter.cs
- Client/src/ArmoniK.DevelopmentKit.Client.Common/Submitter/ClientServiceConnector.cs
- DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Client/ArmonikDataSynapseClientService.cs
- DataSynapseApi/ArmoniK.DevelopmentKit.GridServer.Client/SessionService.cs
- SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Client/api/ArmonikSymphonyClient.cs
- SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi.Client/api/SessionService.cs
- SymphonyApi/ArmoniK.DevelopmentKit.SymphonyApi/SessionPollingService.cs
- Tests/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPITestClient.cs
- UnifiedApi/Client/Factory/SessionServiceFactory.cs
- UnifiedApi/Client/Services/Admin/AdminMonitoringService.cs
- UnifiedApi/Client/Services/SessionService.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
- UnifiedApi/Worker/Grid/SessionPollingService.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi.Common/ArmoniK.DevelopmentKit.WorkerApi.Common.csproj
fix https://github.com/aneoconsulting/ArmoniK/issues/511
> Reuse tasks ids

- Tests/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPIAdminTestClient.cs
- Tests/EndToEnd.Tests/Tests/CheckUnifiedApi/SimpleUnifiedAPITestClient.cs
- UnifiedApi/Client/Factory/ServiceFactory.cs
- UnifiedApi/Client/Services/Admin/ServiceAdmin.cs
- UnifiedApi/Client/Services/Common/AbstractClientService.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
https://github.com/aneoconsulting/ArmoniK/issues/557
> Remove default LoggerFactory

- Tests/EndToEnd.Tests/Tests/CheckGridServer/HeavyPayloadGridServerClient.cs
- Tests/EndToEnd.Tests/Tests/CheckGridServer/SimpleGridServerTestClient.cs
- Tests/EndToEnd.Tests/Tests/CheckMultipleTasks/MultipleTasksClient.cs
- Tests/EndToEnd.Tests/Tests/CheckRandomException/RandomException.cs
- Tests/EndToEnd.Tests/Tests/CheckRandomException/RandomExceptionClient.cs
- Tests/EndToEnd.Tests/Tests/CheckRandomException/RandomExceptionSymClient.cs
- Tests/EndToEnd.Tests/Tests/CheckSubtaskingTree_SymphonySDK/SubtaskingTreeClient.cs
- Tests/EndToEnd.Tests/Tests/CheckTryGetResults/CheckTryGetResultClient.cs
- Tests/EndToEnd.Tests/Tests/CheckTypeOfSubmission/CheckAllSubmissionsClient.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/558
> Reduce EndToEnd tests 

- UnifiedApi/Client/Services/Submitter/Service.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/523
> Cancel result handler before dispose

- UnifiedApi/Client/Services/Submitter/Service.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/559
> Add error details from task in worker for unified api

- Tests/EndToEnd.Tests/Tests/LargePayloadSubmit/LargePayloadSubmit.cs
- Tests/EndToEnd.Tests/Tests/LargePayloadSubmit/LargePayloadSubmitClient.cs
- UnifiedApi/Client/Services/Submitter/Service.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/549
> Add Large Payload test

- UnifiedApi/Client/Services/Submitter/Service.cs
fix https://github.com/aneoconsulting/ArmoniK/issues/566
> Fix issue cancel & error information from client side

- Worker/src/DLLWorker/AppsLoader.cs
- Worker/src/DLLWorker/ServiceRequestContext.cs
- Worker/src/DLLWorker/Services/ComputerService.cs
fix issue https://github.com/aneoconsulting/ArmoniK/issues/626
> Fix issue with UserAssemblyContext unloaded

- Client/src/Common/Submitter/BaseClientSubmitter.cs
- Client/src/Common/Submitter/ClientServiceConnector.cs
- Client/src/Common/Submitter/RequestTaskMap.cs
- Client/src/Unified/Services/Submitter/BlockRequest.cs
- Client/src/Unified/Services/Submitter/Service.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/ArmoniK.EndToEndTests.Client.csproj
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/LargeSubmitAsync/LargeSubmitAsyncTest.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/LargeSubmitAsync/SubmitAsyncFixRequestOrder.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/PayloadIntegrityTestClient/PayloadIntegrityTest.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/PayloadIntegrityTestClient/ResultHandler.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/UnitTestHelperBase.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/PayloadIntegrityTestWorker/Services/ServiceApps.cs
Fix: mapping taskId to submited payload
> Fix mapping taskId to submited payload 

- Client/src/Common/ArmoniK.DevelopmentKit.Client.Common.csproj
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Common/ArmoniK.EndToEndTests.Common.csproj
- Worker/src/Common/ArmoniK.DevelopmentKit.Worker.Common.csproj
This PR update the ArmoniK.Api packages to their latest version.
> update api to 3.3.0

- .dockerignore
- .github/workflows/build.yml
- Worker/src/DLLWorker/Dockerfile
Use buildx to build an arm docker image for worker.
fix https://github.com/aneoconsulting/ArmoniK/issues/863
> ci: build arm docker image

- Client/src/Common/Submitter/BaseClientSubmitter.cs
- Client/src/Unified/Services/Submitter/Service.cs
Fixes https://github.com/aneoconsulting/ArmoniK/issues/901
> fix: Added check for missing tasks

- Client/src/Common/ArmoniK.DevelopmentKit.Client.Common.csproj
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Common/ArmoniK.EndToEndTests.Common.csproj
- Worker/src/Common/ArmoniK.DevelopmentKit.Worker.Common.csproj
Update ArmoniK to 3.6.0:
- LogFunction will show function execution duration
> refactor: update api version to 3.6.0

- Worker/src/Common/Adapter/S3Adapter.cs
- Worker/src/DLLWorker/ServiceRequestContext.cs
[details](https://github.com/aneoconsulting/ArmoniK/issues/959)
tested and approved by Cyrille on his local on prem cluster avec StorageGRID de NetApp
> add force_path_style param in zip s3 config

- Worker/src/Common/ArmoniK.DevelopmentKit.Worker.Common.csproj
Fix issue with missing package when SecurityToken is used on S3
> Fix issue with AWSSDK.SecurityToken

- Client/src/Unified/Services/Common/AbstractClientService.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/CheckUnifiedApi/SimpleUnifiedAPIAdminClientTest.cs
fixes https://github.com/aneoconsulting/ArmoniK/issues/966
> fix: Added view of currently handled task ids in Unified Client

- .github/workflows/semantic-pull-request.yml
fix: https://github.com/aneoconsulting/ArmoniK/issues/987
> add workflow semantic-pull-request.yml

- Client/src/Common/Submitter/BaseClientSubmitter.cs
- Client/src/Unified/Services/Submitter/BatchUntilInactiveBlock.cs
- Client/src/Unified/Services/Submitter/BlockRequest.cs
- Client/src/Unified/Services/Submitter/Service.cs
Main goal is to add more logs and a better management of communication error. Only Mock could reproduce that expected error. In relation with Extensions.Csharp https://github.com/aneoconsulting/ArmoniK/issues/678
> fix: Resend exception when errors occured in SubmitAsync

- Common/src/Common/AppsOptions.cs
- Common/src/Common/ArmoniK.DevelopmentKit.Common.csproj
- Common/src/Common/Utils/FileSpinLock.cs
- Worker/src/Common/Archive/IArchiver.cs
- Worker/src/Common/Archive/ZipArchiver.cs
- Worker/src/Common/IAppsLoader.cs
- Worker/src/Common/ServiceId.cs
- Worker/src/DLLWorker/ApplicationPackageManager.cs
- Worker/src/DLLWorker/AppsLoader.cs
- Worker/src/DLLWorker/ServiceRequestContext.cs
- Worker/src/DLLWorker/Services/ComputerService.cs
Refactored application package loading to handle both zip and local folder
> feat: application package loading for local file handling

- tools/logs2seq.py
Add python script to download logs from local tar archive and send them in seq.
> feat:  Script sending logs in seq
