aneoconsulting/ArmoniK.Extensions.Csharp

- UnifiedApi/Client/Services/Submitter/Service.cs
An exception in errorHandler would bubble up to the get result loop, and thus ends this loop.
A few try-catch have been added to continue to fetch results even in case of errors.
> Add try-catch in GetResult loop

- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/AppsLoader.cs
- WorkerApi/ArmoniK.DevelopmentKit.WorkerApi/Services/ComputerService.cs
This should fix an issue where if the worker is in a bad state (no dll, asked function doesn't exist), the task would still be retried.
Fix based on this flow : https://github.com/aneoconsulting/ArmoniK.Core/blob/main/Documentation/articles/tasks.md
The task will not be retried anymore if such exception arises
fix https://github.com/aneoconsulting/ArmoniK/issues/584
> Fixing issue where an unrecoverable failure of a task could be retried

- Tests/EndToEnd.Tests/Tests/CheckSubtaskingTreeUnifiedApi/SubtaskingTreeUnifiedApiClient.cs
- Tests/EndToEnd.Tests/Tests/CheckSubtaskingTreeUnifiedApi/SubtaskingTreeUnifiedApiWorker.cs
- Tests/EndToEnd.Tests/Tests/CheckSubtaskingTree_SymphonySDK/SubtaskingTreeClient.cs
- UnifiedApi/Worker/Grid/GridWorker.cs
- UnifiedApi/Worker/Grid/ITaskSubmitterWorkerServiceConfiguration.cs
- UnifiedApi/Worker/Grid/TaskSubmitterWorkerService.cs
Rem : 
in Tests/EndToEnd.Tests/Tests/CheckSubtaskingTreeUnifiedApi/SubtaskingTreeUnifiedApiWorker.cs L174
I have wrotten : 
object[] deprot = ProtoSerializer.DeSerializeMessageObjectArray(taskDependency.Value);
var dependencyResultPayload = ClientPayload.Deserialize(deprot[0] as byte[]);
but it's strange for me taskDependency.Value must be my data type but not the internal armonik serialization type
Rem2: TaskSubmitterWorkerService.cs is kind of copy/paste of BaseService<T>.cs
if validated next step to removeBaseService.cs ? or don't touch if Dylan is already refactoring.
goal :
Add possibility to submit task from worker pod/zip(unified API)
Add possibility to submit task with dependencies from worker pod/zip(unified API)
Add EndToEndTest with subtasking (similar to …
> Reinsert submit task for unified api

- Worker/src/DLLWorker/Services/ComputerService.cs
Avoid unnecessary logging in WorkerService
> fix: Set log from info to debug

- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/CheckSubtaskingTreeUnifiedApi/SubtaskingTreeUnifiedApiWorker.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/CheckUnifiedApi/SimpleUnfiedAPITest.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/Tests/PayloadIntegrityTestWorker/Services/ServiceApps.cs
- Worker/src/Unified/GridWorker.cs
- Worker/src/Unified/ILoggerConfiguration.cs
- Worker/src/Unified/ITaskOptionsConfiguration.cs
- Worker/src/Unified/ITaskSubmitterWorkerServiceConfiguration.cs
- Worker/src/Unified/TaskSubmitterWorkerService.cs
just renaming class TaskSubmitterWorkerService  as TaskWorkerService
still keeping old class name as an 'alias' with obsolete tag
> renaming TaskSubmitterWorkerService to TaskWorkerService

- .github/workflows/build.yml
2 points : 
1/ default github image we are using : 'runs-on: ubuntu-latest', already install dotnet versions : https://github.com/actions/runner-images/blob/ubuntu22/20230217.1/images/linux/Ubuntu2204-Readme.md
so in our factory when we are performing dotnet install step : uses: actions/setup-dotnet@v3 in fact v7 is already installed
when we are using dotnet build or pack it is the v7 who is used
2/ in the new 7.0.200 dotnet release : https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0#sdk-and-msbuild
you can see that the -output parameter on solution is deprecated and generate an error : 
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid
=> that's why we have this error : "error NETSDK1194: The "--output" option isn't …
> move pack output files manually

- Common/src/Common/ArmoniK.DevelopmentKit.Common.csproj
Strong name has been added to ArmoniK.Utils in version 0.2.0
> fix: Use strong name for Utils

- .github/workflows/build.yml
- Client/src/Common/Submitter/ClientServiceConnector.cs
Need to fix in ArmoniK.Api. There is no need to override target name when there is no TLS at all
fix: https://github.com/aneoconsulting/ArmoniK/issues/1090
> fix: Issue with no TLS and windows 11

- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/AggregationPriority/AggregationPriorityTest.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Client/Tests/UnitTestHelperBase.cs
The aggregation priority test is too big and doesn't test extc# explicitely, so it should be ignored. This also fixes a configuration of the UnifiedTestHelperBase
> ci: Fixes and reduces nunit tests

- Client/src/Common/Submitter/BaseClientSubmitter.cs
Move channel acquire inside the retry loop to avoid getting the same channel over and over
> fix: Acquire channel within retry loops

- Client/src/Common/Submitter/ChannelPool.cs
Add a health check on the channels upon returning them to the pool, and acquiring one from the pool.
The goal is to force the recreation of a channel if it is unhealthy.
> feat: Add a channel health check for the pool

- Client/src/Common/Properties.cs
Note : The ssl validation now defaults to true if no configuration is given at all.
If a configuration file/ environnement variable is given, then it defaults to it.
If a SSLValidation option is given, then if applies it instead
> fix: Bad property override

- Client/src/Common/ArmoniK.DevelopmentKit.Client.Common.csproj
- Client/src/Common/Submitter/BaseClientSubmitter.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Common/ArmoniK.EndToEndTests.Common.csproj
- Worker/src/Common/ArmoniK.DevelopmentKit.Worker.Common.csproj
This is a first draft for removing the submitter service from the method chunkSubmitWithDependencies. It is the same implementation used in [ArmoniK.Core](https://github.com/aneoconsulting/ArmoniK.Core/blob/main/Tests/HtcMock/Client/src/SessionClient.cs). What is missed in this draft is to label the payloads. 
Another more relevant improvements are possible: submit tasks in a batch not one by one
> refactor: remove submitter from chunk submit with dependencies method

- Client/src/Common/Submitter/TasksClientExt.cs
- Client/src/Unified/Services/Admin/AdminMonitoringService.cs
In this part of the code, I removed the submitter from all the functions except those who takes an argument of type TaskFilter . TaskFilter will be deprecated. 
The functions I updated to not use the submitter need refactoring because I did'nt use ArmoniK filters to filter what output i needed. Instead I received all the outputs then used ."Select" to select the needed output. This code needs refactor to use ArmoniK filters which I began to do but didn't complete. There is one function (ListRunningTasks) where I used ArmoniK Filters. Even when using ArmoniK Filters, a lot of code can be mutualised.
Note also that the format of the code needs to be verified.
> refactor: remove submitter from admin monitoring service

- .github/workflows/build.yml
- Client/src/Common/Exceptions/ResultAbortedException.cs
- Client/src/Common/Submitter/BaseClientSubmitter.cs
- Client/src/Common/Submitter/EventsClientExt.cs
I tried to remove the submitter from the method GetResult that waits for the results before getting them. The implementation for WaitForResults used is the same in [ArmoniK.Api](https://github.com/aneoconsulting/ArmoniK.Api/blob/main/packages/csharp/ArmoniK.Api.Client/EventsClientExt.cs). It uses the events API. Tests did not always pass. There is some unkown and "random" reason that causes the tests to crash sometimes, given that the stream received from the events api was correctly handled.
> refactor: remove submitter from Wait for results method in client part

- Client/src/Common/Submitter/BaseClientSubmitter.cs
```
2024-01-26 10:15:43,786 ERROR 147 ArmoniK.DevelopmentKit.Client.Unified.Services.Submitter.Service - An error occurred while fetching results: System.InvalidOperationException: La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter.
à System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
à System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
à ArmoniK.DevelopmentKit.Client.Common.Submitter.BaseClientSubmitter`1.GetResultStatus(IEnumerable`1 taskIds, CancellationToken cancellationToken)
à ArmoniK.DevelopmentKit.Client.Unified.Services.Submitter.Service.ProxyTryGetResults(IEnumerable`1 taskIds, Action`2 responseHandler, Action`3 errorHandler, Int32 …
```
> fix: Modified collection while enumerating in GetResult

- Client/src/Common/ArmoniK.DevelopmentKit.Client.Common.csproj
- Client/src/Common/Properties.cs
- Client/src/Common/Submitter/ClientServiceConnector.cs
- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Common/ArmoniK.EndToEndTests.Common.csproj
- Worker/src/Common/ArmoniK.DevelopmentKit.Worker.Common.csproj
expose ReusePorts option from https://github.com/aneoconsulting/ArmoniK.Api/pull/524
> fix: ReusePorts

- Worker/src/Common/Adapter/FsAdapter.cs
- Worker/src/Common/Adapter/S3Adapter.cs
- Worker/src/Common/FileExt.cs
If 2 pods are trying to download a zip at the same time, the final move would fail. This fix this behavior by ignoring a moving failure.
> fix: Avoid conflict upon zip move

- .github/workflows/build.yml
Use core version specified in armonik.
This will match the infra version for tests .
This will allow to test in pipeline with latest version in armoniK repository.
> chore: Use core version specified in armonik

- Client/src/Unified/Services/Submitter/Service.cs
Symphony-like SDK supports opening an existing session, but Unified does not.
This PR just exposes opening an existing session to the Unified submitter Service constructor.
> chore: Expose session opening with Unified client

- .github/workflows/build.yml
- Client/src/Unified/Services/Submitter/Service.cs
The current implementation does not release semaphores when the submission fails and does not retry failed result metadate creation.
This PR fixes both issues
> fix: Release when failed submit and retry result creation

- Tests/ArmoniK.EndToEndTests/ArmoniK.EndToEndTests.Worker/DeployWorkerInWsl.ps1
creation of a powershell script to make life easier to the developper that needs to deploy the worker on WSL for endToEnd tests:
- launch dotnet publish on the worker project
- deloy it at the proper location on WSL
- set the control plane url in the appSettings.json of the client project
- restart compute plane pods
> test: automation of worker deployment
